/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppCard: typeof import('@/components/card.vue')['default'];
    AppPageLayout: typeof import('@/components/page-layout.vue')['default'];
    Card: typeof import('./components/card.vue')['default'];
    PageLayout: typeof import('./components/page-layout.vue')['default'];
    VinActionSheet: typeof import('@vingogo/uni-ui/lib/components/action-sheet/index.vue')['default'];
    VinAvatar: typeof import('@vingogo/uni-ui/lib/components/avatar/index.vue')['default'];
    VinAvatarGroup: typeof import('@vingogo/uni-ui/lib/components/avatar-group/index.vue')['default'];
    VinBacktop: typeof import('@vingogo/uni-ui/lib/components/backtop/index.vue')['default'];
    VinBadge: typeof import('@vingogo/uni-ui/lib/components/badge/index.vue')['default'];
    VinButton: typeof import('@vingogo/uni-ui/lib/components/button/index.vue')['default'];
    VinCalendar: typeof import('@vingogo/uni-ui/lib/components/calendar/index.vue')['default'];
    VinCalendarItem: typeof import('@vingogo/uni-ui/lib/components/calendar-item/index.vue')['default'];
    VinCard: typeof import('@vingogo/uni-ui/lib/components/card/index.vue')['default'];
    VinCascader: typeof import('@vingogo/uni-ui/lib/components/cascader/index.vue')['default'];
    VinCascaderItem: typeof import('@vingogo/uni-ui/lib/components/cascader-item/index.vue')['default'];
    VinCategory: typeof import('@vingogo/uni-ui/lib/components/category/index.vue')['default'];
    VinCategoryPane: typeof import('@vingogo/uni-ui/lib/components/category-pane/index.vue')['default'];
    VinCell: typeof import('@vingogo/uni-ui/lib/components/cell/index.vue')['default'];
    VinCellGroup: typeof import('@vingogo/uni-ui/lib/components/cell-group/index.vue')['default'];
    VinCheckbox: typeof import('@vingogo/uni-ui/lib/components/checkbox/index.vue')['default'];
    VinCheckboxGroup: typeof import('@vingogo/uni-ui/lib/components/checkbox-group/index.vue')['default'];
    VinCol: typeof import('@vingogo/uni-ui/lib/components/col/index.vue')['default'];
    VinComment: typeof import('@vingogo/uni-ui/lib/components/comment/index.vue')['default'];
    VinCommentBottom: typeof import('@vingogo/uni-ui/lib/components/comment-bottom/index.vue')['default'];
    VinCommentHeader: typeof import('@vingogo/uni-ui/lib/components/comment-header/index.vue')['default'];
    VinCommentImages: typeof import('@vingogo/uni-ui/lib/components/comment-images/index.vue')['default'];
    VinConfigProvider: typeof import('@vingogo/uni-ui/lib/components/config-provider/index.vue')['default'];
    VinDialog: typeof import('@vingogo/uni-ui/lib/components/dialog/index.vue')['default'];
    VinDivider: typeof import('@vingogo/uni-ui/lib/components/divider/index.vue')['default'];
    VinEmpty: typeof import('@vingogo/uni-ui/lib/components/empty/index.vue')['default'];
    VinFixednav: typeof import('@vingogo/uni-ui/lib/components/fixednav/index.vue')['default'];
    VinForm: typeof import('@vingogo/uni-ui/lib/components/form/index.vue')['default'];
    VinFormItem: typeof import('@vingogo/uni-ui/lib/components/form-item/index.vue')['default'];
    VinGrid: typeof import('@vingogo/uni-ui/lib/components/grid/index.vue')['default'];
    VinGridItem: typeof import('@vingogo/uni-ui/lib/components/grid-item/index.vue')['default'];
    VinIcon: typeof import('@vingogo/uni-ui/lib/components/icon/index.vue')['default'];
    VinInfiniteloading: typeof import('@vingogo/uni-ui/lib/components/infiniteloading/index.vue')['default'];
    VinInput: typeof import('@vingogo/uni-ui/lib/components/input/index.vue')['default'];
    VinInputNumber: typeof import('@vingogo/uni-ui/lib/components/input-number/index.vue')['default'];
    VinList: typeof import('@vingogo/uni-ui/lib/components/list/index.vue')['default'];
    VinNavbar: typeof import('@vingogo/uni-ui/lib/components/navbar/index.vue')['default'];
    VinNoticebar: typeof import('@vingogo/uni-ui/lib/components/noticebar/index.vue')['default'];
    VinNotify: typeof import('@vingogo/uni-ui/lib/components/notify/index.vue')['default'];
    VinOverlay: typeof import('@vingogo/uni-ui/lib/components/overlay/index.vue')['default'];
    VinPopup: typeof import('@vingogo/uni-ui/lib/components/popup/index.vue')['default'];
    VinPrice: typeof import('@vingogo/uni-ui/lib/components/price/index.vue')['default'];
    VinProgress: typeof import('@vingogo/uni-ui/lib/components/progress/index.vue')['default'];
    VinRadio: typeof import('@vingogo/uni-ui/lib/components/radio/index.vue')['default'];
    VinRadiogroup: typeof import('@vingogo/uni-ui/lib/components/radiogroup/index.vue')['default'];
    VinRange: typeof import('@vingogo/uni-ui/lib/components/range/index.vue')['default'];
    VinRate: typeof import('@vingogo/uni-ui/lib/components/rate/index.vue')['default'];
    VinRow: typeof import('@vingogo/uni-ui/lib/components/row/index.vue')['default'];
    VinSearchbar: typeof import('@vingogo/uni-ui/lib/components/searchbar/index.vue')['default'];
    VinSkeleton: typeof import('@vingogo/uni-ui/lib/components/skeleton/index.vue')['default'];
    VinStep: typeof import('@vingogo/uni-ui/lib/components/step/index.vue')['default'];
    VinSteps: typeof import('@vingogo/uni-ui/lib/components/steps/index.vue')['default'];
    VinSwipe: typeof import('@vingogo/uni-ui/lib/components/swipe/index.vue')['default'];
    VinSwiper: typeof import('@vingogo/uni-ui/lib/components/swiper/index.vue')['default'];
    VinSwitch: typeof import('@vingogo/uni-ui/lib/components/switch/index.vue')['default'];
    VinTabbar: typeof import('@vingogo/uni-ui/lib/components/tabbar/index.vue')['default'];
    VinTabbarItem: typeof import('@vingogo/uni-ui/lib/components/tabbar-item/index.vue')['default'];
    VinTabpane: typeof import('@vingogo/uni-ui/lib/components/tabpane/index.vue')['default'];
    VinTabs: typeof import('@vingogo/uni-ui/lib/components/tabs/index.vue')['default'];
    VinTag: typeof import('@vingogo/uni-ui/lib/components/tag/index.vue')['default'];
    VinTextarea: typeof import('@vingogo/uni-ui/lib/components/textarea/index.vue')['default'];
    VinToast: typeof import('@vingogo/uni-ui/lib/components/toast/index.vue')['default'];
    VinTransition: typeof import('@vingogo/uni-ui/lib/components/transition/index.vue')['default'];
    VinUploader: typeof import('@vingogo/uni-ui/lib/components/uploader/index.vue')['default'];
  }
}
